# Generated by Django 2.2.6 on 2020-03-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='Home.Industry'),
            preserve_default=False,
        ),
    ]
